<?php

//Enter your Cakemail credentials below
$cakemail_user = "test@exemple.com";
$cakemail_password = "PASSWORD";

//Path (with trailing slash) to CSV files generated by AzureAD
$csv_path = "";

//$api_hostname = "";
?>